/* tslint:disable */

/**
 ******************************************************************************
 * DO NOT MANUALLY EDIT THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED.
 *
 * IMPORTANT: Due to a bug with the bazel ng_module rule, this file is now
 * checked into the repository. Please rebuild the example module by running
 * the following command: "yarn gulp build-examples-module"
 *
 * BUG: https://github.com/angular/angular/issues/30259
 ******************************************************************************/

import {NgModule} from '@angular/core';

import {FooterOverviewExample} from '@gsa-sam/sds-examples/components/footer';import {FooterExamplesModule} from '@gsa-sam/sds-examples/components/footer';

export interface LiveExample {
  title: string;
  component: any;
  additionalFiles?: string[];
  selectorName?: string;
}

export const EXAMPLE_COMPONENTS: {[key: string]: LiveExample} = {"footer-overview":{"title":"Footer overview","component":FooterOverviewExample,"additionalFiles":[],"selectorName":""}};

export const EXAMPLE_MODULES = [FooterExamplesModule];

export const EXAMPLE_LIST = [FooterOverviewExample];

@NgModule({
  imports: EXAMPLE_MODULES,
  exports: EXAMPLE_MODULES,
  entryComponents: EXAMPLE_LIST,
})
export class ExampleModule { }

// Export all individual example components because ngtsc requires all
// referenced components to be available in the top-level entry-point.
export {FooterOverviewExample}
