/* tslint:disable */

/**
 ******************************************************************************
 * DO NOT MANUALLY EDIT THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED.
 *
 * IMPORTANT: Due to a bug with the bazel ng_module rule, this file is now
 * checked into the repository. Please rebuild the example module by running
 * the following command: "yarn gulp build-examples-module"
 *
 * BUG: https://github.com/angular/angular/issues/30259
 ******************************************************************************/

import {NgModule} from '@angular/core';

import {FocusMonitorDirectivesExample} from '@angular/material-examples/cdk/a11y';import {FocusMonitorFocusViaExample} from '@angular/material-examples/cdk/a11y';import {FocusMonitorOverviewExample} from '@angular/material-examples/cdk/a11y';import {CdkA11yExamplesModule} from '@angular/material-examples/cdk/a11y';

export interface LiveExample {
  title: string;
  component: any;
  additionalFiles?: string[];
  selectorName?: string;
}

export const EXAMPLE_COMPONENTS: {[key: string]: LiveExample} = {"focus-monitor-directives":{"title":"Monitoring focus with FocusMonitor","component":FocusMonitorDirectivesExample,"additionalFiles":[],"selectorName":""},"focus-monitor-focus-via":{"title":"Focusing with a specific FocusOrigin","component":FocusMonitorFocusViaExample,"additionalFiles":[],"selectorName":""},"focus-monitor-overview":{"title":"Monitoring focus with FocusMonitor","component":FocusMonitorOverviewExample,"additionalFiles":[],"selectorName":""}};

export const EXAMPLE_MODULES = [CdkA11yExamplesModule];

export const EXAMPLE_LIST = [FocusMonitorDirectivesExample, FocusMonitorFocusViaExample, FocusMonitorOverviewExample];

@NgModule({
  imports: EXAMPLE_MODULES,
  exports: EXAMPLE_MODULES,
  entryComponents: EXAMPLE_LIST,
})
export class ExampleModule { }

// Export all individual example components because ngtsc requires all
// referenced components to be available in the top-level entry-point.
export {FocusMonitorDirectivesExample, FocusMonitorFocusViaExample, FocusMonitorOverviewExample}
