name: Build Storybook
on:
  workflow_call:
    inputs:
      pr-number:
        required: false
        type: string
jobs:
  Build-Storybook-Assets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install Node Packages
        run: npm ci
      - name: Generate API docs (apidoc)
        run: npm run demo:docs
      - name: Build Stackblitz HTMLs
        run: npm run demo:stackblitzes
      - name: Build Storybook Assets
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
          pr: ${{ inputs.pr-number }}
        run: GH_PAGES=true PR=$pr npm run build-storybook
      - name: Add .nojekyll file to allow for node_modules to be included in bundle
        run: touch storybook-static/.nojekyll
      - name: Archive Storybook Assets
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: storybook-assets
          path: storybook-static
          retention-days: 1
