name: Build Storybook
on:
  workflow_call:
    inputs:
      pr-number:
        required: false
        type: string
jobs:
  Build-Storybook-Assets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install Node Packages
        run: npm i
      - name: Install Global NG CLI
        run: npm install -g @angular/cli@16
      - name: Build Stackblitz HTMLs
        run: npm run demo:stackblitzes
      - name: Build Storybook Assets
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          pr: ${{ inputs.pr-number }}
        run: GH_PAGES=true PR=$pr ng run sam-design-system-site:build-storybook
      - name: Add .nojekyll file to allow for node_modules to be included in bundle
        run: touch storybook-static/.nojekyll
      - name: Archive Storybook Assets
        uses: actions/upload-artifact@v4
        with:
          name: storybook-assets
          path: storybook-static
          retention-days: 1
