name: Continuous Deployment

on:
  push:
    branches:
      - "**"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_matrix:
    runs-on: ubuntu-latest
    outputs:
      json_branches: ${{ steps.generate-matrix.outputs.json_branches }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate Matrix
        id: generate-matrix
        run: |
          branches=($(git branch -r | cut -c 3- | sed 's/origin\///g'))
          json_branches=$(printf '%s\n' "${branches[@]}" | jq -R . | jq -s -c .)
          echo "json_branches=${json_branches}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    name: Build
    needs:
      - build_matrix
    strategy:
      matrix:
        branch: ${{ fromJSON(needs.build_matrix.outputs.json_branches) }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
      - name: Install Node Packages
        run: npm i
      - name: Install Global NG CLI
        run: npm install -g @angular/cli@16
      - name: Build Stackblitz HTMLs
        run: npm run demo:stackblitzes
      - name: Build Storybook Assets
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: GH_PAGES=true BRANCH=${{matrix.branch}} ng run sam-design-system-site:build-storybook
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ strategy.job-index }}
          path: storybook-static
